//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.07 at 06:32:54 AM EAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.mscdemo1.com/spring/soap/api/temp", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mscdemo1.spring.soap.api.temp;
